name: Docker Build & Push Action

on:
  workflow_dispatch:
  push:
      branches:
        - main

jobs: 
  build-rtems-5:
    # Continue if checks-for-duplicates found no duplicates. Always runs for
    # pull-requests.
    
    name: Build and Push Container
    runs-on: ubuntu-latest
    
    steps:                     
      - name: Checkout code
        uses: actions/checkout@v2        

      - name: Build and Push 
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: qemu-rtems-5
          dockerfile: rtems-5/Dockerfile
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

build-rtems-4.11:
    # Continue if checks-for-duplicates found no duplicates. Always runs for
    # pull-requests.
    
    name: Build and Push Container
    runs-on: ubuntu-latest
    
    steps:                     
      - name: Checkout code
        uses: actions/checkout@v2        

      - name: Build and Push 
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: qemu-rtems-4.11
          dockerfile: rtems-4.11/Dockerfile
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
